version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/frontend"
    versioning-strategy: increase-if-necessary
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 50
  - package-ecosystem: "gomod"
    directory: "/src/backend"
    schedule:
      interval: "weekly"